<?php include __DIR__ . "/header.phtml"; ?>
<div class="container">

    <h2>Posts Cadastrados</h2>

    <div class="row">
        <div class="col col-lg-9 col-md-9 col-sm-9 col-12">
            <ul class="list-unstyled">
                <li>
                    <?php foreach ($posts as $posts) { ?>

                        <div class="jumbotron">
                            <h1>
                                <?= $posts->getTitulo(); ?>
                            </h1>
                            <p>
                                <?= substr($posts->getTexto(), 0, 20); ?>
                                ...
                            </p>
                            <p>
                                <a href="#" class="btn btn-primary" role="button">
                                    Leia mais
                                </a>
                            </p>
                        </div>

                    <?php } ?>
                </li>
            </ul>
        </div>
        <div class="col col-lg-3 col-md-3 col-sm-3 col-12">
            <ul class="list-group">
                <?php foreach ($categorias as $categorias) { ?>
                    <li class="list-group-item">
                        <a href="/?search=<?= $categorias->getId(); ?>">
                            <?= $categorias->getNome(); ?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>


</div>
<?php include __DIR__ . "/footer.phtml"; ?>