<?php include __DIR__ . "/../header.phtml"; ?>
<div class="container">
    <div class="row">
        <h3>Cadastrar Categoria</h3>
        <form action="/categorias/store" method="POST">
            <div class="form-group">
                <label>Nome da Categoria</label>
                <input type="text" id="nome" name="nome" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
    </div>
</div>
<?php include __DIR__ . "/../footer.phtml"; ?>