<?php include __DIR__ . "/../header.phtml"; ?>
<div class="container">
    <div class="row">
        <h3>Editar Post</h3>
        <form action="<?php echo "/posts/{$posts->getId()}/update"; ?>" method="POST">
            <div class="form-group">
                <label>Titulo do Post</label>
                <input type="text" id="titulo" name="titulo" class="form-control" value="<?= $posts->getTitulo(); ?>" required>
            </div>
            <div class="form-group">
                <label>Texto</label>
                <textarea id="texto" name="texto" class="form-control"><?= $posts->getTexto(); ?></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
    </div>
</div>
<?php include __DIR__ . "/../footer.phtml"; ?>
